# Generated by Django 4.2.5 on 2024-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadrashaSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=150)),
                ('add_photo', models.ImageField(upload_to='madrashaslider/')),
                ('details_of_photo', models.TextField()),
            ],
        ),
    ]
